default: pipe socket mem_share

pipe: pipe.c
	gcc pipe.c -o pipe

socket: socket.c
	gcc socket.c -lpthread -lm -lrt -o socket

mem_share: mem_share.c
	gcc mem_share.c -lpthread -lm -lrt -o mem_share

